name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  build_troublesome:
    name: build unicode_string
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - name: Check
        run: nix build --print-build-logs .#unicode_string
