name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - name: Get dependencies
        run: nix develop .#ci --command -- mix deps.get
      - name: Dialyze
        run: nix develop .#ci --command -- mix dialyzer
      - name: Run tests
        run: nix develop .#ci --command -- mix test
      - name: Check fixture derivations
        run: nix flake check
